app/urls.py
from flask import Blueprint
from app.auth import view as auth_view
from app.posts import view as posts_view
from app.users import view as users_view


blueprint = Blueprint('bp', __name__)



# auth URLs
AUTH_PREFIX = '/auth'
blueprint.add_url_rule(AUTH_PREFIX + '/register', view_func=auth_view.RegisterUser.as_view('register_user'))
blueprint.add_url_rule(AUTH_PREFIX + '/login', view_func=auth_view.LoginUser.as_view('login_user'))
blueprint.add_url_rule(AUTH_PREFIX + '/update', view_func=auth_view.UpdateUser.as_view('update_user'))
blueprint.add_url_rule(AUTH_PREFIX + '/logout', view_func=auth_view.LogoutUser.as_view('logout_user'))
blueprint.add_url_rule(AUTH_PREFIX + '/reset', view_func=auth_view.ResetPassword.as_view('reset_password'))
blueprint.add_url_rule(AUTH_PREFIX + '/check_reset_token', view_func=auth_view.CheckResetToken.as_view('check_reset_token'))
blueprint.add_url_rule(AUTH_PREFIX + '/deactivate/<int:user_id>', view_func=auth_view.DeleteUser.as_view('deactivate_user'))

# posts URLs
POSTS_PREFIX = '/posts'
blueprint.add_url_rule(POSTS_PREFIX + '/home/<int:page>', view_func=posts_view.PostList.as_view('posts_list'))
blueprint.add_url_rule(POSTS_PREFIX + '/create',view_func=posts_view.CreatePost.as_view('create_post'))
blueprint.add_url_rule(POSTS_PREFIX + '/delete/<int:post_id>', view_func=posts_view.DeletePost.as_view('delete_post'))
blueprint.add_url_rule(POSTS_PREFIX + '/update/<int:post_id>', view_func=posts_view.UpdatePost.as_view('update_post'))
blueprint.add_url_rule(POSTS_PREFIX + '/detail/<int:post_id>', view_func=posts_view.PostDetail.as_view('post_detail'))
blueprint.add_url_rule(POSTS_PREFIX + '/react/', view_func=posts_view.ReactPost.as_view('react_post'))
blueprint.add_url_rule('/', view_func=posts_view.Home.as_view('start'))

#users URLs
USERS_PREFIX = '/users'
blueprint.add_url_rule(USERS_PREFIX + '/profile', view_func=users_view.Profile.as_view('profile'))

app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileField, FileAllowed


class PostForm(FlaskForm):
	title = StringField('Title',validators=[DataRequired()])
	content = StringField('Content',validators=[DataRequired()])
	video = StringField('Video Link	',validators=[Length(min=0,max=80)])
	photo1 = FileField('Add photo',validators=[FileAllowed(['jpg', 'png'])])
	submit = SubmitField('Submit')

class UpdatePostForm(FlaskForm):
	title = StringField('Title', validators=[DataRequired()])
	content = StringField('Content',validators=[DataRequired()])
	video = StringField('Video Link',validators=[Length(min=0,max=80)])
	photo1 = FileField('Add photo',validators=[FileAllowed(['jpg', 'png'])])
	submit = SubmitField('Update')

class StartForm(FlaskForm):
	submit = SubmitField('Get Started')	

app/posts/controllers.py
from config import Config
from datetime import datetime

class PostController:

	def __init__(self):
		self.db_conn = Config.SQLITE_CONN

	def save_post_data(self, post_data):
		current_datetime = datetime.now().strftime("%Y-%m-%d")
		post_data.update({'created_at': current_datetime})
		query = '''insert into posts (title, content,created_at, user_id, video)
					values ("{title}","{content}","{created_at}","{user_id}","{video}")'''.format(**post_data)
		self.db_conn.write_db(query)

	def save_post_data_with_image(self,post_data):
		current_datetime = datetime.now().strftime("%Y-%m-%d")
		post_data.update({'created_at': current_datetime})
		query = '''insert into posts (title, content,created_at, user_id, video,photo1)
					values ("{title}","{content}","{created_at}","{user_id}","{video}","{photo1}")'''.format(**post_data)
		self.db_conn.write_db(query)

	def fetch_paginated_post(self, page):
		query = '''select p.*, u.instagram, u.username, u.avatar,u.twitter,u.quora, ri.rating_action
					from posts as p 
					left join users u on u.id = p.user_id
					left join rating_info ri on ri.user_id = p.user_id and ri.post_id = p.id 
					order by p.created_at desc
					limit 5 offset {}'''.format((page-1)*5)
		return self.db_conn.query_db(query)

	def fetch_posts_count(self):
		query = '''select count(1) as posts_count from posts'''
		return self.db_conn.query_db_one(query)

	def get_detail(self,post_id):
		query = '''select * from posts where id = "{}"'''.format(post_id)
		return self.db_conn.query_db_one(query)	

	def del_post(self,post_id):
		query = '''delete from posts where id = "{}"'''.format(post_id)
		return self.db_conn.write_db(query)

	def get_post_by_id(self,post_id):
		query = '''select * from posts where id = "{}"'''.format(post_id)
		print(query)
		return self.db_conn.query_db_one(query)

	def update_post(self,post_data):
		query = '''update posts set title="{title}",content="{content}","video"="{video}" where id = "{id}"'''.format(**post_data)
		return self.db_conn.write_db(query)

	def update_post_with_image(self,post_data):
		query = '''update posts set title="{title}",content="{content}","video"="{video}","photo1"="{photo1}" where id = "{id}"'''.format(**post_data)
		return self.db_conn.write_db(query)

	def get_postid_by_userid(self,user_id):
		query = '''select post_id from rating_info where user_id={}'''.format(user_id)
		return self.db_conn.query_db(query)	

	def get_status_of_rating(self,post_id,user_id):
		query = '''select rating_action from rating_info where post_id = {} and user_id = {}'''.format(post_id,user_id)
		print(query)
		return self.db_conn.query_db_one(query) 

	def insert_reaction(self,user_id,post_id,action):
		query = '''insert into rating_info (user_id,post_id,rating_action)	values ({},{},"{}")'''.format(user_id,post_id,action)
		print(query)
		return self.db_conn.write_db(query)

	def update_like(self,post_id,action):
		if action=='like':
			query = '''update posts set like=like+1 where id = {}'''.format(post_id)
			print(query)
			return self.db_conn.write_db(query)
		elif action=='dislike':
			query = '''update posts set unlike=unlike+1 where id = {}'''.format(post_id)
			print(query)
			return self.db_conn.write_db(query)	

	def update_reaction(self,user_id,post_id,action):
		query = '''update rating_info set user_id={}, post_id={}, rating_action="{}"'''.format(user_id,post_id,action)
		print(query)
		return self.db_conn.write_db(query)

	def del_reaction(self,user_id,post_id):
		query = '''delete from rating_info where user_id = {} and post_id = {} '''.format(user_id,post_id)
		print(query)
		return self.db_conn.write_db(query)

	def delete_like(self,post_id,action):
		if action=='unlike':
			query = '''update posts set like=like-1 where id = {}'''.format(post_id)
			print(query)
			return self.db_conn.write_db(query)
		elif action=='undislike':
			query = '''update posts set unlike=unlike-1 where id = {}'''.format(post_id)
			print(query)
			return self.db_conn.write_db(query)

app/users/controllers.py
from config import Config


class UserController:
	def __init__(self):
		self.db_conn = Config.SQLITE_CONN

	def get_all_post_of_user(self,user_id):
		query = '''select * from posts where user_id = "{}"'''.format(user_id)
		return self.db_conn.query_db(query)

	def get_user_detail(self,user_id):
		query = '''select * from users where id = "{}"'''.format(user_id)
		return self.db_conn.query_db_one(query)

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://use.fontawesome.com/f2711bfaa9.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    <script type="text/javascript" src="{{ url_for('static',filename='js/app.js') }}"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css/"> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a href="#" class="navbar-brand">
            <img src="https://thumbs.dreamstime.com/z/blogging-neon-text-vector-design-template-blog-logo-light-banner-element-colorful-modern-trend-night-bright-advertising-sign-144268595.jpg" width="50"  height="50" alt="CoolBrand">
          </a>
          <a class="navbar-brand mr-4" href="{{ url_for('bp.posts_list', page=1) }}" style="font-family: 'Molle', cursive;">Blogger</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if user_id %}
              <a class="nav-item nav-link" href="{{ url_for('bp.profile') }}" style="font-family: 'Molle', cursive;">My Posts</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user_id %}
                <a class="nav-item nav-link" href="{{ url_for('bp.create_post') }}" style="font-family: 'Molle', cursive;">Create Post</a>
                <a class="nav-item nav-link" href="{{ url_for('bp.update_user') }}" style="font-family: 'Molle', cursive;">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('bp.logout_user') }}" style="font-family: 'Molle', cursive;">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('bp.login_user') }}" style="font-family: 'Molle', cursive;">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('bp.register_user') }}" style="font-family: 'Molle', cursive;">Register</a>
              {% endif %}      
            </div>
          </div>
        </div>
      </nav>
    </header>
    {% if title=='register' %}
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="https://images.pexels.com/photos/185933/pexels-photo-185933.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="First slide" width="500" height="550">
            <div class="carousel-caption d-none d-md-block">
              <h4 style="font-size:55px; font-family:Poppins; letter-spacing:2px; color:black;">Hang onto your memories</h4>
              <p style="font-size:20px; font-family:Poppins; color:black;">Save the moments that matter. Blogger lets you safely store thousands of posts for free.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="http://www.weebly.com/uploads/6/7/9/5/6795120/7069944_orig.png" alt="Second slide" width="500" height="550">
            <div class="carousel-caption d-none d-md-block">
              <h4 style="font-size:55px; font-family:Poppins; letter-spacing:2px; color:black;">Publish your passions, your way</h4>
              <p style="font-size:20px; font-family:Poppins; color:black;">Create a unique and beautiful blog. It’s easy and free.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="https://images.pexels.com/photos/128299/pexels-photo-128299.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="Third slide" width="500" height="550">
            <div class="carousel-caption d-none d-md-block">
              <h4 style="font-size:55px; font-family:Poppins; letter-spacing:2px; color:white;">Join others</h4>
              <p style="font-size:20px; font-family:Poppins; color:white;">Whether sharing your expertise, breaking news, or whatever’s on your mind, you’re in good company on Blogger. Sign up to discover people have published their passions here.</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    {% endif %}      
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
    </main>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  var captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += "active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>
</body>
</html>

app/templates/posts/create.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.video.label(class="form-control-label") }}
                {% if form.video.errors %}
                    {{ form.video(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.video.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.video(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">  
                {{ form.photo1 }}
                {% if form.photo1.errors %}
                    {% for error in form.photo1.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

app/templates/posts/detail.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    {% if user_data.avatar %}
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile/'+user_data.avatar) }}">
    {% else %}
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile/'+'default.jpg') }}">
    {% endif %}
    <div class="media-body">
      <div class="article-metadata">
        
        <small class="text-muted">{{ post.created_at }}</small>        
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('bp.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
      {% if post.photo1 %}
      <img src="{{ url_for('static', filename='profile/'+post.photo1) }}">
      {% endif %}
      {% if post.video %}
      <p class="article-content"><iframe width="420" height="345" src='{{ post.video }}'frameborder="0" allowfullscreen></iframe></p>
      {% endif %}
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete the Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('bp.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/posts/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          {% if post.avatar %}
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile/'+ post.avatar) }}">
          {% else %}
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile/'+ 'default.jpg') }}">
          {% endif %}
          <div class="media-body">
            <div class="article-metadata">
              <small class="text-muted">{{ post.username }}</small>
              <small class="text-muted">{{ post.created_at }}</small>
              {% if post.instagram %}
              <a href={{ post.instagram }}><i class="fab fa-instagram"></i></a>
              {% endif %}
              {% if post.twitter %}
              <a href={{ post.twitter }}><i class="fab fa-twitter"></i></a>
              {% endif %}
              {% if post.quora %}
              <a href={{ post.quora }}><i class="fab fa-quora"></i></a>
              {% endif %}
            </div>
            <h2><a class="article-title">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            {% if post.photo1 and post.video %}
            <div class="container">
              <div class="mySlides">
                <img src="{{ url_for('static', filename='profile/'+post.photo1) }}">
              </div>                
              <div class="mySlides">
                <iframe width="420" height="345" src='{{ post.video }}'frameborder="0" allowfullscreen></iframe>
              </div>
              <a class="prev" onclick="plusSlides(-1)">❮</a>
              <a class="next" onclick="plusSlides(1)">❯</a>
            </div>
            {% endif %}
          </div>
          {% if user_id %}
            <div> 
              {% if post.id in arr %}
                {% if post.rating_action == 'like' %}
                  <button class="fa fa-thumbs-up like-btn" data-id="{{ post.id }}"></button>
                  <span id="post_like_{{post.id}}">{{ post.like }}</span>
                  <button class="fa fa-thumbs-o-down dislike-btn" data-dislike-id="{{ post.id }}"></button>
                  <span id="post_unlike_{{post.id}}">{{post.unlike}}</span>
                {% elif post.rating_action == 'dislike' %}
                  <button class="fa fa-thumbs-o-up like-btn" data-id="{{ post.id }}"></button>
                  <span id="post_like_{{post.id}}">{{ post.like }}</span>
                  <button class="fa fa-thumbs-down dislike-btn" data-dislike-id="{{ post.id }}"></button>
                  <span id="post_unlike_{{post.id}}">{{post.unlike}}</span>  
                {% endif %}
              {% else %}
                <button class="fa fa-thumbs-o-up like-btn" data-id="{{ post.id }}"></button>
                <span id="post_like_{{post.id}}">{{ post.like }}</span>
                <button class="fa fa-thumbs-o-down dislike-btn" data-dislike-id="{{ post.id }}"></button>
                <span id="post_unlike_{{post.id}}">{{post.unlike}}</span>
              {% endif %}
            </div>
          {% endif %}
        </article>
    {% endfor %}
    {% for pages in range(1,page_num) %}
      <a class="btn btn-info mb-4" href="{{ url_for('bp.posts_list', page=pages) }}">{{ pages }}</a>
    {% endfor %}  
{% endblock content %}

app/templates/posts/start.html
<!DOCTYPE html>
<html>
<head>
	<title>Blogger - Start</title>
</head>
<body>
	<div class="content-section">
        <form method="POST" action="">
        	{{ form.hidden_tag() }}
        	<div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
</body>
</html>

app/templates/posts/updatepost.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.video.label(class="form-control-label") }}
                {% if form.video.errors %}
                    {{ form.video(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.video.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.video(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">  
                {{ form.photo1 }}
                {% if form.photo1.errors %}
                    {% for error in form.photo1.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

app/templates/users/profile.html
{% extends "layout.html" %}
{% block content %}
<h1>{{ user_data.username }} Posts</h1>
<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('bp.deactivate_user', user_id=user_data.id) }}">Deactivate</a>
    {% for post in posts %}
        <article class="media content-section">
          {% if user_data.avatar %}
          <img class="rounded-circle article-img" src="{{url_for('static',filename='profile/'+user_data.avatar) }}">
          {% else %}
          <img class="rounded-circle article-img" src="{{url_for('static',filename='profile/'+'default.jpg') }}">
          {% endif %}
          <div class="media-body">
            <div class="article-metadata">
              <small class="text-muted">{{ post.created_at }}</small>
              <a href={{ post.instagram }}><i class="fa fa-instagram" style="font-size:36px"></i></a>
            </div>
            <h2><a class="article-title" href="{{url_for('bp.post_detail',post_id=post.id)}}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            {% if post.video %}
            <p class="article-content"><iframe width="420" height="345" src='{{ post.video }}'frameborder="0" allowfullscreen></iframe></p>
            {% endif %}
          </div>
        </article>
    {% endfor %}
{% endblock content %}